version: '3.8'

services:
  app:
    build: .
    ports:
      - "8081:8081" # Metro bundler
      - "19000:19000" # Expo
      - "19001:19001"
      - "19002:19002"
    volumes:
      - .:/app             # Syncs your folder with the container
      - /app/node_modules # Prevents local node_modules from overwriting container's
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP}
      # - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      # - ADB_IP=host.docker.internal # Optional: For connecting to emulator
    # This keeps the container running so you can enter it
    stdin_open: true 
    tty: true
